server:
  port: 4000

spring:
  application:
    name: DeepFXServer
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://database-1.cekg2t7qwqmr.ap-northeast-2.rds.amazonaws.com/DeepFX
    username: admin
    password: q3143118
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      platform: mysql
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    credentials:
      access-key: AKIAXZF3GNJ5RO2E4EXD
      secret-key: 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
    s3:
      bucket: deepfx
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
